name: 🐛 Bug
description: Something is not working as expected or not working at all! Report it here!
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this issue report. Please check existing issues first before continuing.
  - type: textarea
    id: verbatim
    validations:
      required: true
    attributes:
      label: "What is not working as expected?"
      description: "Describe what the issue is."
  - type: textarea
    id: expect
    validations:
      required: true
    attributes:
      label: "What did you expect to happen?"
      description: "A clear and concise description of what you expected to happen."
  - type: textarea
    id: reproduce
    validations:
      required: true
    attributes:
      label: "How can we reproduce it?"
      description: "Detailed steps to reproduce the issue. Logs are always helpful."
  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: Describe your environment 
      description: "Kubernetes version, Helm version, installation commands etc."
  - type: textarea
    id: version
    validations:
      required: true
    attributes:
      label: What is the version of your Peerd?
      description: ""
  - type: checkboxes
    id: idea
    attributes:
      label: "Are you willing to submit PRs to contribute to this bug fix?"
      description: "This is absolutely not required, but we are happy to guide you in the contribution process
        especially when you already have a good proposal or understanding of how to implement it."
      options:
        - label: Yes, I am willing to implement it.      